export const ProductsDatas = [
    {
        'code': 1001,
        'id': 1,
        'name': 'Burger Asiatique',
        'note': 'Extra Sauce',
        'price': 12.5,
        'devise': '$',
        'available': 12,
        'urlImage': '/products/br-1.jpeg',
        'id_category': 1,

    },
    {
        'code': 1002,
        'id': 2,
        'name': 'Burger Afrique',
        'note': 'Extra Egg',
        'price': 12.5,
        'devise': '$',
        'available': 20,
        'urlImage': '/products/br-2.jpeg',
        'id_category': 1,

    },
    {
        'code': 1003,
        'id': 3,
        'name': 'Burger French',
        'note': 'With Mayo',
        'price': 20.5,
        'devise': '$',
        'available': 10,
        'urlImage': '/products/br-3.jpeg',
        'id_category': 1,

    },
    {
        'code': 1004,
        'id': 4,
        'name': 'Burger Indian',
        'note': 'with Mustard',
        'price': 9.5,
        'devise': '$',
        'available': 10,
        'urlImage': '/products/br-4.jpeg',
        'id_category': 1,

    },
    {
        'code': 1005,
        'id': 5,
        'name': 'Noodles Indian',
        'note': 'with Mustard',
        'price': 9.5,
        'devise': '$',
        'available': 10,
        'urlImage': '/products/ns-1.jpeg',
        'id_category': 2,

    },
    {
        'code': 1006,
        'id': 6,
        'name': 'Noodles Red',
        'note': 'prawn noodles',
        'price': 4.5,
        'devise': '$',
        'available': 9,
        'urlImage': '/products/ns-2.jpeg',
        'id_category': 2,

    },
    {
        'code': 1007,
        'id': 7,
        'name': 'Strawberries Cold Drink',
        'note': 'sweet',
        'price': 4.5,
        'devise': '$',
        'available': 10,
        'urlImage': '/products/dr-1.png',
        'id_category': 3,

    },
    {
        'code': 1008,
        'id': 8,
        'name': 'Chocolate Drink',
        'note': 'with sugar',
        'price': 8.5,
        'devise': '$',
        'available': 7,
        'urlImage': '/products/dr-2.webp',
        'id_category': 3,

    },
    {
        'code': 1009,
        'id': 9,
        'name': 'Dessert',
        'note': 'without sugar',
        'price': 4.5,
        'devise': '$',
        'available': 9,
        'urlImage': '/products/ds-1.webp',
        'id_category': 4,

    },
    {
        'code': 1010,
        'id': 10,
        'name': 'Dessert',
        'note': 'without sugar',
        'price': 6.5,
        'devise': '$',
        'available': 4,
        'urlImage': '/products/ds-2.png',
        'id_category': 4,

    },
    {
        'code': 1011,
        'id': 11,
        'name': 'Burger Asiatique',
        'note': 'Extra Sauce',
        'price': 12.5,
        'devise': '$',
        'available': 12,
        'urlImage': '/products/br-1.jpeg',
        'id_category': 1,

    },
    {
        'code': 1012,
        'id': 12,
        'name': 'Burger Afrique',
        'note': 'Extra Egg',
        'price': 12.5,
        'devise': '$',
        'available': 20,
        'urlImage': '/products/br-2.jpeg',
        'id_category': 1,

    },
    {
        'code': 1013,
        'id': 13,
        'name': 'Burger French',
        'note': 'With Mayo',
        'price': 20.5,
        'devise': '$',
        'available': 10,
        'urlImage': '/products/br-3.jpeg',
        'id_category': 1,

    },
    {
        'code': 10001,
         'id': 14,
        'name': 'Burger Asiatique',
        'note': 'Extra Sauce',
        'price': 12.5,
        'devise': '$',
        'available': 12,
        'urlImage': '/products/br-1.jpeg',
        'id_category': 1,

    },
    {
        'code': 10001,
         'id': 15,
        'name': 'Burger Afrique',
        'note':'Extra Egg',
        'price': 12.5,
        'devise': '$',
        'available': 20,
        'urlImage': '/products/br-2.jpeg',
        'id_category': 1,

    },
    {
        'code': 10001,
         'id': 16,
        'name': 'Burger French',
        'note':'With Mayo',
        'price': 20.5,
        'devise': '$',
        'available': 10,
        'urlImage': '/products/br-3.jpeg',
        'id_category': 1,

    },
    {
        'code': 10001,
         'id': 17,
        'name': 'Burger Asiatique',
        'note': 'Extra Sauce',
        'price': 12.5,
        'devise': '$',
        'available': 12,
        'urlImage': '/products/br-1.jpeg',
        'id_category': 1,

    },
    {
        'code': 10001,
         'id': 18,
        'name': 'Burger Afrique',
        'note':'Extra Egg',
        'price': 12.5,
        'devise': '$',
        'available': 20,
        'urlImage': '/products/br-2.jpeg',
        'id_category': 1,

    },
    {
        'code': 10001,
        'id': 19,
        'name': 'Burger French',
        'note':'With Mayo',
        'price': 20.5,
        'devise': '$',
        'available': 10,
        'urlImage': '/products/br-3.jpeg',
        'id_category': 1,

    }
]